#!/bin/sh

set -e

# Automatically added by dh_installinit/13.10
if [ "$1" = "remove" ] && [ -x "/etc/init.d/pulseaudio-enable-autospawn" ] ; then
	chmod -x "/etc/init.d/pulseaudio-enable-autospawn" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d pulseaudio-enable-autospawn remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemduser/13.10
if [ "$1" = "purge" ]; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'pulseaudio.service' 'pulseaudio.socket' >/dev/null || true
	fi
fi
# End automatically added section


if [ "$1" = "purge" ] ; then
        deluser --quiet --system pulse > /dev/null || true
        delgroup --quiet --system pulse-access > /dev/null || true
        delgroup --quiet --system pulse-rt > /dev/null || true
fi

exit 0
