#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.RealtimeKit1.conf 0.12-1\~ rtkit -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'rtkit-daemon.service' >/dev/null || true
fi
# End automatically added section
