#! /bin/sh
# postinst script for rtkit

set -e

case "$1" in
  configure)
    if ! getent passwd rtkit >/dev/null; then
      adduser --disabled-password  --quiet --system \
        --home /proc --no-create-home \
        --gecos "RealtimeKit" --group rtkit
    fi

    if [ -x "/etc/init.d/dbus" ]; then
      invoke-rc.d dbus force-reload || true
    fi
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.RealtimeKit1.conf 0.12-1\~ rtkit -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'rtkit-daemon.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'rtkit-daemon.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'rtkit-daemon.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'rtkit-daemon.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'rtkit-daemon.service' >/dev/null || true
fi
# End automatically added section


exit 0
